name: sick_rags_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  bot_toast: ^4.0.4
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  flutter_phoenix: ^1.1.1
  cloud_firestore: ^4.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
